### ISSUE TITLE
[Persona] Create section component

### ISSUE THREAD

**Issue by mimibak** [mimibak/portfolio_lab#1]
## Description
As a developer, I want to merge the three container components into one main component, so that the application renders a single persona component in the root element of index.html.

### Visibility:
The index.html contains three different element components for the persona section. The user can see the persona-about- persona-contact-info- and persona-title-component.
The persona-contact-info includes the persona-socialmedia component.

### with Result:
User has one main persona-component which will be inserted to the root element of the index.html. the main persona-component includes persona-about-, persona-contact-info- and persona-title-component. 

### without Result:
User will get an "error" feedback/message, why the content is not shown. 

## Acceptance Criteria
- [x] the main component contains persona-component includes persona-about-, persona-contact-info- and persona-imgJob-component. 
- [x] the browser shows all datas which is requested from the db.json

# Task
- [x] create a main-persona-component (Persona.js in view folder)
- [x] import all existing persona-components to the main-persona-component
- [x] replace all three persona-components in the root element of the index.html with the main-persona-component
- [x] add error handling to the main-persona-component
